//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twitterClone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweet
    {
        public int Id { get; set; }
        public string status { get; set; }
        public string detailedDescription { get; set; }
        public string userPosted { get; set; }
        public System.DateTime postedDateTime { get; set; }
    }
}
